---
title: "EpiEstim x R0"
author: "Christine Sangphet"
date: "2024-07-24"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **EpiEstim x R0**

```{r}
# load environment

library(EpiEstim)
library(ggplot2)
library(gridExtra)
library(incidence)
library(R0)
```

```{r}
#load data

data(Flu2009)
```

### **Estimations with EpiEstim**

```{r}
res_parametric_si <- estimate_R(Flu2009$incidence, 
                                method="parametric_si",
                                config = make_config(list(
                                  mean_si = 2.6, 
                                  std_si = 1.5))
)
```

```{r}
plot(res_parametric_si)
```

### **Estimations with R0**

#### SI

```{r}
Flu2009$si_distr
```

```{r}
GT.chld.hsld1<-generation.time("empirical", c(0.000,0.233,0.359,0.198,0.103,0.053,0.027,0.014,0.007,0.003,0.002,0.001))

GT.chld.hsld1
plot(GT.chld.hsld1)
```

#### R

```{r}
data("Germany.1918")
print(Germany.1918)
```

```{r}
Flu2009$incidence
```

```{r}
#change Flu2009$incidence format

library(dplyr)

colnames(Flu2009$incidence) <- c("dates", "incid")

# Convert the dates column to character format for column names
date_vector <- as.character(Flu2009$incidence$dates)
incid_vector <- Flu2009$incidence$incid

# Create a named vector for the matrix
incid_new_format <- setNames(incid_vector, date_vector)

print(incid_new_format, quote = FALSE)

```

```{r}
mGT<-generation.time("gamma", c(2.6, 1.5))
est.R0.ML(incid_new_format, mGT, begin=1, end=32)
```

```{r}
res = est.R0.ML(incid_new_format, mGT, begin=1, end=27, range=c(0.01,50))
plot(res)
```

```{r}
TD <- est.R0.TD(incid_new_format, mGT, begin=8, end=30, nsim=1000)
```

```{r}
TD
```

```{r}
plot(TD)
```

### Comparison of SI estimation

#### Side-by-side

```{r}
library(cowplot)

plot1 <- plot(res_parametric_si, "SI")

plot2 <- plot(GT.chld.hsld1)

grid.arrange(plot1, plot2, ncol = 1)
```

#### Overlay

```{r}
#turn epiestim SI into dataframe

si_data <- data.frame(si_distr = res_parametric_si$si_distr[0:11],
                      time = 0:10)

#turn R0 SI into dataframe

mean_gt <- 2.596
sd_gt <- 1.534531

shape <- (mean_gt / sd_gt)^2
scale <- (sd_gt^2) / mean_gt

time_values <- 0:10
gamma_values <- dgamma(time_values, shape = shape, scale = scale)

r0_data <- data.frame(time = time_values, r0_values = gamma_values)

#combine the plots

plot <- ggplot() +
 geom_line(data = si_data, aes(x = time, y = si_distr, color = "EpiEstim"), size = 1) +
  geom_line(data = r0_data, aes(x = time, y = r0_values, color = "R0"), size = 1) +
  scale_color_manual(name = "Legend", values = c("EpiEstim" = "blue4", "R0" = "lightblue1")) +
  theme_bw() +
  labs(title = "Serial Interval",
       x = "Days after onset",
       y = "Probability")

plot
```

### Comparison of R estimation

#### Side-by-side

```{r}
plot3 <- plot(res_parametric_si, "R")

plot4 <- plot(TD)

grid.arrange(plot3, plot4, ncol = 1)
```

#### Overlay

```{r}
#turn TD$R into a dataframe

dates <- c("2009-05-04", "2009-05-05", "2009-05-06", "2009-05-07", "2009-05-08", "2009-05-09", 
           "2009-05-10", "2009-05-11", "2009-05-12", "2009-05-13", "2009-05-14", "2009-05-15", 
           "2009-05-16", "2009-05-17", "2009-05-18", "2009-05-19", "2009-05-20", "2009-05-21", 
           "2009-05-22", "2009-05-23", "2009-05-24", "2009-05-25", "2009-05-26")

R_values <- c(1.4431534, 1.5281943, 1.9150867, 1.9332333, 1.5755135, 1.1801216, 
              0.9678166, 0.7906301, 0.6478225, 0.5225889, 0.4846133, 0.3834813, 
              0.2713710, 0.2770432, 0.3921351, 0.0000000, 0.7650676, 0.0000000, 
              0.0000000, 0.0000000, 0.0000000, 1.2471919, 0.0000000)


df_r0 <- data.frame(dates, R_values)


print(df_r0)
```

```{r}
#turn epiestim R into a dataframe 

names(res_parametric_si$R)

r_data <- data.frame(
  t = Flu2009$incidence$dates[8:30],
  mean_r = c(res_parametric_si$R$`Mean(R)`)[1:23],
  quantile_0_025_r = c(res_parametric_si$R$`Quantile.0.025(R)`)[1:23],
  quantile_0_975_r = c(res_parametric_si$R$`Quantile.0.975(R)`)[1:23]
)

#dataframe for R0

r0_r <- data.frame(
  r0_t = as.Date(c(df_r0$dates)),
  r0_mean = c(df_r0$R_values),
  r0_lwr = c(TD$conf.int$lower),
  r0_upr = c(TD$conf.int$upper)
)

#combine

plot2 <- ggplot() +
  geom_line(data = r_data, aes(x = t, y = mean_r, color = "EpiEstim")) +
  geom_ribbon(data = r_data, aes(x = t, ymin = quantile_0_025_r, ymax = quantile_0_975_r), alpha = 0.2, fill = "black") +
  geom_line(data = r0_r, aes(x = r0_t, y = r0_mean, color = "R0")) +
  geom_ribbon(data = r0_r, aes(x = r0_t, ymin = r0_lwr, ymax = r0_upr), alpha = 0.2, fill = "violetred") +
   scale_color_manual(name = "Legend", values = c("EpiEstim" = "black", "R0" = "violetred")) +
  
  labs(title = "Estimated R",
       x = "Date",
       y = "R")

plot2
```
