---
title: "EpiLPS Testing"
author: "Christine Sangphet"
date: "2024-07-07"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load environment

devtools::install_github("oswaldogressani/EpiLPS")
library(EpiLPS)
```

# Specification of a serial interval and data generation

```{r}
#The Idist() function computes the probability density function and probability mass function for a disease interval based on the mean and standard deviation of the disease interval (expressed in days)

si_spec <- Idist(mean = 2.7, sd = 1.3, dist = "gamma")
si <- si_spec$pvec
si
```

```{r}
plot(si_spec)
```

```{r}
#using the above serial interval, we can call the episim() routine to generate a time series of incidence data (say for an epidemic lasting 40 days).

set.seed(123)
datasim <- episim(si = si, Rpattern = 5, endepi = 40, dist = "negbin", overdisp = 15, plotsim = TRUE)
```

```{r}
incidence <- datasim$y
incidence
```

# Estimation of the reproduction number

```{r}
#The code below defines an object called LPSfit from the estimR() routine. the latter object is a list with many different components summarizing the results of the fit. Among this list, the RLPS component is of particular interest as it gives a summary of the estimated reproduction number (point estimates and selected quantiles).

LPSfit <- estimR(incidence = incidence, si = si)
class(LPSfit)
```

```{r}
knitr::kable(tail(LPSfit$RLPS[,1:7]))
```

```{r}
#The estimR() routine generates an object of class Rt and there are two S3 methods associated with an object of that class, namely a summary() method and a plot() method. The former gives:

summary(LPSfit)
```

```{r}
plot(LPSfit)
```

```{r}
#The estimRmcmcm() routine works similarly. By default it draws 5000 MCMC samples and uses a burn-in of size 2000. Being a fully stochastic approach, the latter routine is slower than estimR().

LPSfitmcmc <- estimRmcmc(incidence = incidence, si = si, niter = 5000, burnin = 2000)
```

```{r}
summary(LPSfitmcmc)
```

```{r}
#By specifying the addfit = "Cori" option in the S3 plot method, we can overlay both estimates

LPSfit2 <- estimR(incidence = incidence, si = si, CoriR = TRUE)
knitr::kable(tail(LPSfit2$RCori[,1:7]))
```

```{r}
plot(LPSfit2, addfit = "Cori")
```

```{r}
#the estimated reproduction number can also be potted by extracting values from the LPSfit2 object in a traditional way as shown below

tt <- seq(8, 40, by = 1)
Rtrue <- sapply(tt, datasim$Rtrue)
plot(tt, Rtrue, type = "l", xlab = "Time", ylab = "R", ylim = c(0,4),
     lwd = 2)
lines(tt, LPSfit2$RLPS$R[-(1:7)], col = "red", lwd = 2)
lines(tt, LPSfit2$RCori$`Mean(R)`, col = "blue", lwd = 2)
legend("topright", col = c("black","red","blue"), 
       c("True R","EpiLPS","EpiEstim"), bty = "n", lty = c(1,1,1))
```

# Customizing graphical output

```{r}
library(ggplot2)

gridExtra::grid.arrange(
  plot(LPSfit, col = "firebrick", legendpos = "top", cicol = "orange"),
  plot(LPSfit, col = "forestgreen", legendpos = "none", cicol = "green",
       theme = "light", title = "Reproduction number"),
  plot(LPSfit, col = "darkblue", legendpos = "none", cicol = "orchid",
       theme = "classic"),
  plot(LPSfit, col = "white", legendpos = "none", cicol = "gray",
       theme = "dark"),
  nrow = 2, ncol = 2)
```

# Illustration on the Zika virus in Girardot, Colombia (2015)

```{r}
library(outbreaks)

#the data is loaded and the epidemic curve is visualized with the epicurve() routine

zika <- zika_girardot_2015
plotIncidence <- epicurve(zika$cases, dates = zika$date, datelab = "14d", title = "Zika incidence")
plotIncidence
```

```{r}
#A serial interval distribution of mean 7 days (SD=1.5 days) is specified and the estimR() routine is used to estimate the reproduction number

si <- Idist(mean = 7, sd = 1.5)
siplot <- plot(si, titlesize = 11)
epifit <- estimR(zika$cases, dates = zika$date, si = si$pvec)
summary(epifit)
```

```{r}
#the estimation results are summarized into a single plot

plotsmooth <- epicurve(zika$cases, dates = zika$date, datelab = "14d", smooth = epifit, smoothcol = "orange", title = "Zika incidence (smoothed)")

# Plot of the estimated reproduction number
Rplot <- plot(epifit, datelab = "7d", xtickangle = 70, legendpos = "none", col = "forestgreen")

# Show all plots together
gridExtra::grid.arrange(plotIncidence, plotsmooth, siplot, Rplot, nrow = 2, ncol = 2)
```

# Illustration on outbreaks considered in Cori et al. (2013)

```{r}
library(EpiEstim)
library(epiR)
library(gridExtra) 
```

```{r}
data("Flu1918")

fluDAT <- Flu1918

flu_incid <- fluDAT$incidence

flu_si <- fluDAT$si_distr[-1]

epifit_flu <- estimR(flu_incid, si = flu_si, CoriR = TRUE)

epicurve_flu <- epicurve(flu_incid, datelab = "7d", title = "Influenza, Baltimore, 1918",
                            col = "orange", smooth = epifit_flu, smoothcol = "firebrick")

Rplot_flu <- plot(epifit_flu, legendpos = "none")

Rplot_flu2 <- plot(epifit_flu, addfit = "Cori", legendpos = "top")

siplot_flu <- plot(Idist(probs = flu_si), barcol = "indianred1")

gridExtra::grid.arrange(epicurve_flu, Rplot_flu, Rplot_flu2, 
                        siplot_flu, nrow = 2, ncol = 2)
```
