---
title: "Package_Research_File"
author: "Christine Sangphet"
date: "2024-06-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Initial Steps

```{r}
# Install package
library('findPackage')
```

```{r}
# output packages need to be worked on 

findPackage('reproduction number')
```

```{r}
#

install.packages('earlyR')
```

```{r}
#

install.packages('EpiNow2')
```

```{r}
install.packages('covid19india')
```

```{r}
install.packages('epitrix')
```

```{r}
install.packages('projections')
```

```{r}
install.packages('modelSSE')
```

```{r}
install.packages('R0')
```

```{r}
install.packages('ern')
```

```{r}
install.packages('epigrowthfit')
```

```{r}
findPackage('reproduction number')
```

```{r}
findPackage('reproduction number')
```

```{r}
findPackage('epidemic')
```

```{r}
install.packages('EpiILMCT')
```

```{r}
findPackage('epidemic')
```

```{r}
install.packages('epimdr')
```

```{r}
install.packages('EpiILM')
```

```{r}
findPackage('epi')
```

```{r}
findPackage('infectious disease')
```

```{r}
install.packages('EpiLPS')
```

```{r}
install.packages('RtEstim')
```
